//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avavav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Согласие.
    /// </summary>
    // *** Start programmer edit section *** (Согласие CustomAttributes)

    // *** End programmer edit section *** (Согласие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СогласиеE", new string[] {
            "Номер as \'Номер\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фио as \'Фио\'",
            "Сотрудники.Телефон as \'Телефон\'",
            "Сотрудники.Номер as \'Номер сотрудника\'"}, Hidden=new string[] {
            "Сотрудники.Фио"})]
    [MasterViewDefineAttribute("СогласиеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио")]
    [View("СогласиеL", new string[] {
            "Номер as \'Номер\'",
            "Сотрудники.Фио as \'Фио\'",
            "Сотрудники.Номер as \'Номер сотрудника\'",
            "Сотрудники.Телефон as \'Телефон сотрудника\'"})]
    public class Согласие : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Avavav.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Согласие CustomMembers)

        // *** End programmer edit section *** (Согласие CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Номер CustomAttributes)

        // *** End programmer edit section *** (Согласие.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Номер Get start)

                // *** End programmer edit section *** (Согласие.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Согласие.Номер Get end)

                // *** End programmer edit section *** (Согласие.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Номер Set start)

                // *** End programmer edit section *** (Согласие.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Согласие.Номер Set end)

                // *** End programmer edit section *** (Согласие.Номер Set end)
            }
        }
        
        /// <summary>
        /// Согласие.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Согласие.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Avavav.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Get start)

                // *** End programmer edit section *** (Согласие.Сотрудники Get start)
                IIS.Avavav.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Согласие.Сотрудники Get end)

                // *** End programmer edit section *** (Согласие.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Set start)

                // *** End programmer edit section *** (Согласие.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Согласие.Сотрудники Set end)

                // *** End programmer edit section *** (Согласие.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СогласиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеE", typeof(IIS.Avavav.Согласие));
                }
            }
            
            /// <summary>
            /// "СогласиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеL", typeof(IIS.Avavav.Согласие));
                }
            }
        }
    }
}
